export const EXECUTION_EVENT_TYPES = [
  "task.created",
  "task.state_changed",
  "task.blocked",
  "task.completed",
  "role_runtime.created",
  "role_runtime.state_changed",
  "executor_session.started",
  "executor_session.completed",
  "executor_session.failed",
  "model.resolved",
  "model.fallback_applied",
  "approval.created",
  "approval.resolved",
  "artifact.created",
  "channel.message_received",
  "channel.message_sent",
  "memory.candidate_created",
  "leader.session_checkpoint",
  "leader.tool_call",
  "leader.tool_result",
  "leader.session_complete",
  "leader.teammate_spawned",
  "leader.teammate_completed",
  "leader.session_resumed",
  "leader.recovery_attempted",
  "leader.messages_compacted",
  "leader.mailbox_consumed",
  "leader.plan_mode_entered",
  "leader.plan_proposed",
  "leader.plan_mode_exited",
] as const;

export type ExecutionEventType = (typeof EXECUTION_EVENT_TYPES)[number];
